// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {IncrementalMerkleTreeV2} from "./IncrementalMerkleTreeV2.sol";
import {IUnifiedTransferVerifier, IUnifiedWithdrawVerifier} from "./interfaces/IUnifiedVerifier.sol";

/// @dev Minimal ERC20 interface -- transfer + transferFrom only.
interface IERC20Unified {
    function transferFrom(address from, address to, uint256 amount) external returns (bool);
    function transfer(address to, uint256 amount) external returns (bool);
}

/// @dev Minimal Poseidon(1) interface for asset_id computation.
///      ABI: poseidon(uint256[1]) -> uint256
interface IPoseidonT2 {
    function poseidon(uint256[1] calldata) external pure returns (uint256);
}

/**
 * @title UnifiedShieldedPool
 * @notice Multi-token shielded pool on Avalanche C-Chain.
 *
 * A single Merkle tree holds commitments for ALL supported ERC20 tokens.
 * Each note commitment encodes the token type via an `asset_id` field:
 *
 *   asset_id = Poseidon(uint256(token_address))
 *   note_commitment = Poseidon(C.x, C.y, secret, nullifier_preimage, owner_pk.x, asset_id)
 *
 * Privacy properties:
 *   - Deposits: token + amount + depositor address are PUBLIC (ERC20 transfer is visible)
 *   - Transfers: FULLY PRIVATE -- amount, sender, receiver, AND token type are hidden
 *   - Withdrawals: token + amount + recipient are PUBLIC (required to release ERC20)
 *
 * Anonymity set = ALL users across ALL tokens (not per-token like V1 single pools).
 *
 * Merkle tree: depth 24, Poseidon(t=3), 16M leaf capacity, 100 historical roots.
 *
 * @dev Requires two Groth16 verifier contracts (auto-generated by snarkjs):
 *        - transferVerifier: verifies UnifiedTransfer proofs (4 public inputs)
 *        - withdrawVerifier: verifies UnifiedWithdraw proofs (5 public inputs)
 *
 *      Poseidon contracts must use identical parameters to circomlib circuits.
 *      Any mismatch = all proofs fail.
 */
contract UnifiedShieldedPool {
    using IncrementalMerkleTreeV2 for IncrementalMerkleTreeV2.TreeData;

    // -----------------------------------------------------------------------
    // Errors
    // -----------------------------------------------------------------------
    error TokenNotAllowed(address token);
    error InvalidMerkleRoot();
    error NullifierAlreadySpent(uint256 nullifier);
    error InvalidTransferProof();
    error InvalidWithdrawProof();
    error ZeroAmount();
    error InsufficientPoolBalance(address token, uint256 requested, uint256 available);
    error TokenAlreadyAllowed(address token);
    error ZeroAddress();
    error NotOwner();

    // -----------------------------------------------------------------------
    // Events
    // -----------------------------------------------------------------------

    /// @notice Emitted when tokens are deposited into the shielded pool
    event Deposit(
        uint256 indexed commitment,
        uint256 leafIndex,
        uint256 amount,
        address indexed token,
        uint256 assetId,
        uint256 timestamp
    );

    /// @notice Emitted when a private transfer occurs inside the pool
    event PrivateTransfer(
        uint256 indexed nullifier,
        uint256 newCommitment1,
        uint256 newCommitment2,
        bytes encryptedMemo1,
        bytes encryptedMemo2
    );

    /// @notice Emitted when tokens are withdrawn from the shielded pool
    event Withdrawal(
        uint256 indexed nullifier,
        address indexed recipient,
        uint256 amount,
        address indexed token,
        uint256 changeCommitment,
        bytes encryptedMemo
    );

    /// @notice Emitted when a new token is whitelisted
    event TokenAdded(address indexed token, uint256 assetId);

    // -----------------------------------------------------------------------
    // State
    // -----------------------------------------------------------------------

    address public owner;

    IUnifiedTransferVerifier public immutable transferVerifier;
    IUnifiedWithdrawVerifier public immutable withdrawVerifier;
    IPoseidonT2 public immutable poseidonT2;

    IncrementalMerkleTreeV2.TreeData internal tree;

    mapping(uint256 => bool) public spentNullifiers;
    mapping(address => bool) public allowedTokens;
    mapping(address => uint256) public tokenAssetId;
    mapping(address => uint256) public poolBalance;
    address[] public allowedTokenList;

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    /// @param _transferVerifier  Deployed UnifiedTransferVerifier
    /// @param _withdrawVerifier  Deployed UnifiedWithdrawVerifier
    /// @param _poseidonT2        Deployed Poseidon(1) contract for asset_id
    /// @param _poseidonT3        Deployed Poseidon(2) contract for Merkle tree
    constructor(
        address _transferVerifier,
        address _withdrawVerifier,
        address _poseidonT2,
        address _poseidonT3
    ) {
        require(_transferVerifier != address(0), "USP: zero transfer verifier");
        require(_withdrawVerifier != address(0), "USP: zero withdraw verifier");
        require(_poseidonT2 != address(0), "USP: zero poseidonT2");
        require(_poseidonT3 != address(0), "USP: zero poseidonT3");

        owner = msg.sender;
        transferVerifier = IUnifiedTransferVerifier(_transferVerifier);
        withdrawVerifier = IUnifiedWithdrawVerifier(_withdrawVerifier);
        poseidonT2 = IPoseidonT2(_poseidonT2);
        tree.init(_poseidonT3);
    }

    // -----------------------------------------------------------------------
    // Modifiers
    // -----------------------------------------------------------------------

    modifier onlyOwner() {
        if (msg.sender != owner) revert NotOwner();
        _;
    }

    // -----------------------------------------------------------------------
    // Admin
    // -----------------------------------------------------------------------

    /// @notice Whitelist a new ERC20 token for the pool
    function addToken(address token) external onlyOwner {
        if (token == address(0)) revert ZeroAddress();
        if (allowedTokens[token]) revert TokenAlreadyAllowed(token);

        allowedTokens[token] = true;

        // asset_id = Poseidon(uint256(token_address))
        uint256 assetId = poseidonT2.poseidon([uint256(uint160(token))]);
        tokenAssetId[token] = assetId;
        allowedTokenList.push(token);

        emit TokenAdded(token, assetId);
    }

    /// @notice Transfer ownership
    function transferOwnership(address newOwner) external onlyOwner {
        if (newOwner == address(0)) revert ZeroAddress();
        owner = newOwner;
    }

    // -----------------------------------------------------------------------
    // Deposit
    // -----------------------------------------------------------------------

    /// @notice Deposit ERC20 tokens into the shielded pool
    /// @param token          ERC20 token to deposit
    /// @param amount         Amount to deposit
    /// @param noteCommitment V2 note commitment (includes asset_id)
    function deposit(
        address token,
        uint256 amount,
        uint256 noteCommitment
    ) external {
        if (!allowedTokens[token]) revert TokenNotAllowed(token);
        if (amount == 0) revert ZeroAmount();

        bool success = IERC20Unified(token).transferFrom(msg.sender, address(this), amount);
        require(success, "ERC20 transfer failed");

        (uint32 leafIndex, ) = tree.insert(noteCommitment);
        poolBalance[token] += amount;

        emit Deposit(
            noteCommitment,
            leafIndex,
            amount,
            token,
            tokenAssetId[token],
            block.timestamp
        );
    }

    // -----------------------------------------------------------------------
    // Transfer
    // -----------------------------------------------------------------------

    /// @notice Execute a private transfer inside the shielded pool
    function transfer(
        uint256[2] calldata proof_a,
        uint256[2][2] calldata proof_b,
        uint256[2] calldata proof_c,
        uint256 merkleRoot,
        uint256 nullifierHash,
        uint256 newCommitment1,
        uint256 newCommitment2,
        bytes calldata encryptedMemo1,
        bytes calldata encryptedMemo2
    ) external {
        if (!tree.isKnownRoot(merkleRoot)) revert InvalidMerkleRoot();
        if (spentNullifiers[nullifierHash]) revert NullifierAlreadySpent(nullifierHash);

        if (!transferVerifier.verifyProof(
            proof_a, proof_b, proof_c,
            [merkleRoot, nullifierHash, newCommitment1, newCommitment2]
        )) {
            revert InvalidTransferProof();
        }

        spentNullifiers[nullifierHash] = true;
        tree.insert(newCommitment1);
        tree.insert(newCommitment2);

        emit PrivateTransfer(
            nullifierHash,
            newCommitment1,
            newCommitment2,
            encryptedMemo1,
            encryptedMemo2
        );
    }

    // -----------------------------------------------------------------------
    // Withdraw
    // -----------------------------------------------------------------------

    /// @notice Withdraw ERC20 tokens from the shielded pool
    function withdraw(
        uint256[2] calldata proof_a,
        uint256[2][2] calldata proof_b,
        uint256[2] calldata proof_c,
        uint256 merkleRoot,
        uint256 nullifierHash,
        uint256 amount,
        uint256 changeCommitment,
        address token,
        address recipient,
        bytes calldata encryptedMemo
    ) external {
        if (!allowedTokens[token]) revert TokenNotAllowed(token);
        if (amount == 0) revert ZeroAmount();
        if (recipient == address(0)) revert ZeroAddress();
        if (!tree.isKnownRoot(merkleRoot)) revert InvalidMerkleRoot();
        if (spentNullifiers[nullifierHash]) revert NullifierAlreadySpent(nullifierHash);

        uint256 expectedAssetId = tokenAssetId[token];

        if (!withdrawVerifier.verifyProof(
            proof_a, proof_b, proof_c,
            [merkleRoot, nullifierHash, amount, changeCommitment, expectedAssetId]
        )) {
            revert InvalidWithdrawProof();
        }

        if (poolBalance[token] < amount) {
            revert InsufficientPoolBalance(token, amount, poolBalance[token]);
        }

        spentNullifiers[nullifierHash] = true;

        if (changeCommitment != 0) {
            tree.insert(changeCommitment);
        }

        poolBalance[token] -= amount;
        bool success = IERC20Unified(token).transfer(recipient, amount);
        require(success, "ERC20 transfer failed");

        emit Withdrawal(
            nullifierHash,
            recipient,
            amount,
            token,
            changeCommitment,
            encryptedMemo
        );
    }

    // -----------------------------------------------------------------------
    // View functions
    // -----------------------------------------------------------------------

    function getRoot() external view returns (uint256) {
        return tree.getRoot();
    }

    function getNextLeafIndex() external view returns (uint32) {
        return tree.nextIndex;
    }

    function isSpentNullifier(uint256 nullifier) external view returns (bool) {
        return spentNullifiers[nullifier];
    }

    function isKnownRoot(uint256 root) external view returns (bool) {
        return tree.isKnownRoot(root);
    }

    function getPoolBalance(address token) external view returns (uint256) {
        return poolBalance[token];
    }

    function getAssetId(address token) external view returns (uint256) {
        return tokenAssetId[token];
    }

    function isTokenAllowed(address token) external view returns (bool) {
        return allowedTokens[token];
    }

    function getAllowedTokenCount() external view returns (uint256) {
        return allowedTokenList.length;
    }

    function getAllowedToken(uint256 index) external view returns (address) {
        return allowedTokenList[index];
    }
}
